### PR TITLE
Catch Throwable in ErrorProneScanner

### PR DESCRIPTION
**Pull request by stevie400**
We're getting `java.lang.ExceptionInInitializerError` and failing the build.

@Xcelled @suruuK @jaredstehler

### CODE REVIEW

**Comment by jaredstehler** [comment]
does this supercede https://github.com/HubSpot/error-prone/pull/85

**Comment by stevie400** [comment]
oh, I forgot that was still open

**Comment by jaredstehler** [comment]
closing in favor of merging #85

**Comment by jaredstehler** [comment]
closing in favor of merging #85

**Pull request closed without merging**
